[package]
name = "ratatui-rat-trap"
version = "0.1.0"
authors = ["kevinbednarek <kevinbednarek@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
emojis = "0.6.2"
rand = "0.8.5"
ratatui = "0.26.0"
